export default [
  {
    id: 1,
    userId: 1,
    title: "할일1",
    doneAt: null,
    createdAt: new Date(),
    updatedAt: "null",
  },
  {
    id: 2,
    userId: 2,
    title: "할일1",
    doneAt: null,
    createdAt: new Date(),
    updatedAt: "null",
  },
  {
    id: 3,
    userId: 2,
    title: "할일2",
    doneAt: null,
    createdAt: new Date(),
    updatedAt: "null",
  },
  {
    id: 4,
    userId: 2,
    title: "할일3",
    doneAt: null,
    createdAt: new Date(),
    updatedAt: "null",
  },
  {
    id: 5,
    userId: 2,
    title: "할일4",
    doneAt: null,
    createdAt: new Date(),
    updatedAt: "null",
  },
];
