import mysql from 'mysql2/promise'
import { faker } from '@faker-js/faker/locale/en';
import "dotenv/config"
import {fa} from "@faker-js/faker";

const connection = await mysql.createConnection({
        host: process.env.DB_HOST,
        user: process.env.DB_USER,
        password: process.env.DB_PASSWORD,
        database: process.env.DB_DATABASE,
    })

// measure time
console.time("read")
const names = [
    "우준호",
        "213",
        "213",
        "woojunho",
        "woo dent",
        "woo dent",
        "우우우",
        "이름",
        "12345",
        "902134",
        "3333",
        "3333",
        "12121212",
        "4444",
        "5555",
        "6666",
        "7777",
        "8888",
        "2222",
        "121212",
        "2345",
        "1111",
        "Katrina Grant MD",
        "Paulette Runte",
        "Vera Deckow",
        "Mr. Frank Hoeger",
        "Alexis Nader",
        "Jodi Parisian Jr.",
        "Danielle Doyle",
        "Rebecca Gibson",
        "Marcella Schneider V",
        "Kelly Mante V",
        "Lorena Hayes",
        "Van Robel",
        "Erika Rice",
        "Eric Harber",
        "Dr. Tracy Williamson",
        "Alfredo Cole",
        "Alex O'Connell",
        "Jeanne Schimmel",
        "Nancy Marks",
        "Jana Trantow",
        "Ivan Braun",
        "Elsa Hegmann",
        "Guadalupe Lubowitz",
        "Franklin Abernathy II",
        "Jim Crist",
        "Mr. Gilberto Rutherford DVM",
        "Catherine Shanahan",
        "Kristina Hartmann",
        "Emmett Lueilwitz-Boyer",
        "Shawna Leannon",
        "Shawn Schaefer",
        "Dr. Brittany Schaefer",
        "Yolanda Murphy",
        "Cody Corkery",
        "Mr. Darin Schaden",
        "Lori Hauck",
        "Virgil Schaden",
        "Ms. Kristin O'Reilly-Harber II",
        "Judith Howe",
        "Joe Fahey",
        "Sonja Daniel",
        "Joanna Mitchell",
        "Evelyn Cormier",
        "Sylvia Adams",
        "Alonzo Reichert",
        "Janet Farrell",
        "Sadie Lockman V",
        "Antoinette Sauer",
        "Estelle Kessler-Douglas",
        "Angelina Schinner IV",
        "Darrin Schowalter",
        "Andy Hane",
        "Cory Raynor",
        "Adrian Howe",
        "Mr. Kenneth Mraz",
        "Mr. Ervin Jacobs",
        "Cindy Dare",
        "Josh Nolan",
        "Ervin Veum",
        "Dr. Jason Senger III",
        "Matthew Bednar",
        "Melanie Greenholt",
        "Saul Bode",
        "Joy Welch",
        "Joanne Shanahan",
        "Ramiro Hills MD",
        "Wilma Grady-Pacocha",
        "Lewis Stiedemann",
        "Sheila Hackett",
        "Preston Krajcik",
        "Jerome Kozey",
        "Mr. Eric Gerhold",
        "Jean Roob I",
        "Bobby Fisher",
        "Cary Kovacek-Hilll",
        "Armando Mayer",
        "Miss Juanita Schimmel",
        "Kenny Tillman",
        "Delbert Christiansen",
        "Jerry Schmitt",
        "Mrs. Penny Emard",
        "Leigh Greenfelder",
        "Warren Ortiz V",
        "Marion Harris PhD",
        "Norman Bauch",
        "Monique Hamill",
        "Jeffrey Parker DDS",
        "Amanda Hand I",
        "Pablo Abbott",
        "Kristin Watsica",
        "Beulah Kshlerin",
        "Cary Armstrong",
        "Lynne Kunze",
        "Archie Botsford",
        "Patty Nienow",
        "Gregg Sipes",
        "Lester Labadie",
        "Bill Cartwright",
        "Lamar Fay",
        "Bridget Kub",
        "Sabrina Altenwerth",
        "Mario Hauck",
        "Grant Kuhlman",
        "Melba Johns",
        "Muriel Zieme",
        "Mandy Schmitt",
        "Cindy Gutmann",
        "Morris Kerluke",
        "Bradley Simonis",
        "Georgia Emmerich",
        "Dominick Weissnat",
        "Tiffany Sanford",
        "Eunice Schinner",
        "Harvey Sporer",
        "Marion Greenholt",
        "Ashley Waters",
        "Lee Gleichner",
        "Belinda McKenzie",
        "Stuart Schuppe",
        "June Quigley II",
        "Juan Schmeler Sr.",
        "Sheila Tromp",
        "Tammy McDermott",
        "Ms. Marcia Senger DVM",
        "Ismael Walsh",
        "Frank King",
        "Joe Nikolaus",
        "Todd Morissette",
        "Lindsay Dare",
        "Duane Kohler",
        "Mr. Roderick Zemlak PhD",
        "Teri King",
        "Tyrone Lesch DVM",
        "Diana Botsford IV",
        "Jenna O'Conner MD",
        "Melvin Witting",
        "Jessie Metz",
        "Dana Stark",
        "Alma O'Connell",
        "Ismael Brown",
        "Kerry Pouros",
        "Jesus Stamm",
        "Charles Robel",
        "Austin Zulauf",
        "Sherri Howe",
        "Eddie Hand",
        "Kelly Walter",
        "Jeanette Mayer",
        "Neal Morar",
        "Tomas Vandervort",
        "Catherine Windler",
        "Alexander Collins",
        "Karen Hahn",
        "Van Quigley",
        "Brandy Konopelski",
        "Mercedes Toy",
        "Yvette Nienow",
        "Nina Keebler",
        "Alyssa Spinka",
        "Jacquelyn Blick",
        "Dr. Guy Lubowitz",
        "Dan Nader",
        "Delbert Hoeger",
        "Charlie Terry",
        "Mark Marvin",
        "Miss Jacqueline Braun",
        "Shirley MacGyver",
        "Jamie Barrows",
        "Anna Heidenreich",
        "Luke Bednar",
        "Ira Parker",
        "Tiffany Prosacco",
        "Geraldine Hilpert",
        "Amber Farrell IV",
        "Mr. Wilbert Morar",
        "Ella Effertz DDS",
        "Max Lubowitz",
        "Allen Jerde",
        "Charles Von",
        "Eric Block",
        "Alex Reichel",
        "Tommie Roberts",
        "Leah Altenwerth",
        "Ms. Lorena Farrell",
        "Lynne Botsford",
        "Lula Anderson",
        "Brittany Cruickshank",
        "Olive Ullrich",
        "Julie Price",
        "Brian Baumbach",
        "Irma Cummings",
        "Henry Murphy",
        "Mercedes Quigley",
        "Whitney Wintheiser",
        "Mrs. Lisa Schaefer",
        "Sylvester Schultz",
        "Lynda Littel",
        "Krista Ondricka",
        "Woodrow Lebsack",
        "Maxine Kautzer",
        "Della MacGyver",
        "Edith Wuckert",
        "Morris Durgan",
        "Meghan MacGyver",
        "Georgia Bechtelar",
        "Angelina Larson",
        "Gwen Hayes",
        "Peter Mohr",
        "Della Breitenberg",
        "Mrs. Carol Halvorson",
        "Jaime Zulauf",
        "Alan Breitenberg",
        "Floyd Von",
        "Mark Cartwright",
        "Laurie Turner",
        "Lois Steuber",
        "Eva Howell",
        "Edwin Mayer",
        "Rebecca Hagenes",
        "Dora Gorczany",
        "Jean Hansen",
        "Aubrey Harris",
        "Rose Cassin",
        "Rudy Mann",
        "Barbara Conroy",
        "Arnold Hegmann",
        "Tasha Koss",
        "Jermaine Hintz-Zemlak",
        "Luther Gibson",
        "Jason Lesch",
        "Elizabeth Connelly",
        "Rafael Bashirian",
        "Gwen Bernhard",
        "Helen Spencer",
        "Alvin Schumm",
        "Bonnie Bruen PhD",
        "Andy Murray",
        "Mr. Gabriel Labadie",
        "Daniel Bogan IV",
        "Jill Rosenbaum",
        "Merle Botsford",
        "Dr. Nina Hirthe",
        "Mr. Edmond Russel",
        "Jordan Beatty",
        "Marcia Veum",
        "Stuart Hudson",
        "Debbie Hahn",
        "Rafael Kuhn",
        "Claude McLaughlin V",
        "Tiffany Klocko",
        "Cameron Leffler Sr.",
        "Marco McKenzie",
        "Rosemarie Spencer",
        "Christina Rohan",
        "Ellen Powlowski MD",
        "Shawna Gutmann",
        "Delia Gislason MD",
        "Sheila Conroy",
        "Maureen Zboncak",
        "Norman Carroll",
        "Amanda Stamm",
        "Kellie Casper Sr.",
        "Micheal Hackett",
        "Irma Balistreri-Barton",
        "Andrew Bosco",
        "Tracy Hudson",
        "Edgar Schroeder",
        "Greg Crooks",
        "Larry Fadel",
        "Lawrence Parker",
        "Jo Lebsack",
        "Alan Crooks",
        "Ricardo Roob",
        "Janis Jaskolski PhD",
        "Mr. Salvatore Champlin",
        "Veronica Hayes",
        "Angie Kuhlman",
        "Lisa Ondricka IV",
        "Tasha Rippin",
        "Elsie Ruecker",
        "Alan Kiehn",
        "Mr. Henry Kovacek",
        "Lynne Gibson",
        "Kay Weber",
        "Lorraine Kling",
        "Neal Hane MD",
        "Wilma Pfeffer",
        "Mr. Guadalupe Kshlerin",
        "Marie Kessler",
        "Tammy Lowe",
        "Wendy Streich",
        "Dr. Lance Reynolds",
        "Rafael Johnson Jr.",
        "Colin Littel",
        "Kristi Harris",
        "Edward Monahan",
        "Douglas Carter",
        "Mabel Reinger",
        "Jessica Carter",
        "Ben Herman",
        "Joann Altenwerth",
        "Alberta Pagac-Labadie",
        "Dr. Jimmie Miller",
        "Lillie Macejkovic",
        "Duane Considine",
        "Sheila Blick",
        "Leslie Ebert",
        "Edith Little III",
        "Rafael Stroman",
        "Darrin Koss II",
        "Rafael Robel",
        "Julia Hegmann",
        "Suzanne Streich",
        "Eula Aufderhar",
        "Patti Mraz",
        "Brooke Murazik",
        "Eula Harris DDS",
        "Eugene Ebert",
        "Ronald Conroy",
        "Clara Powlowski",
        "Harry Rogahn",
        "Bertha Schumm",
        "Trevor Stehr",
        "Angelica Reinger II",
        "Dwight Kuhic",
        "Isabel Stiedemann",
        "Herbert Weissnat-Brekke",
        "Martin Brown",
        "Nora Hermiston",
        "Marcella Jenkins-Marquardt",
        "Danielle Muller",
        "Dr. Conrad Stiedemann",
        "Miss Irene Kautzer",
        "Carl Denesik",
        "Leticia Nolan",
        "Cedric Zemlak",
        "Myra Stanton",
        "Mr. Ken Klocko",
        "Grady Will",
        "Lorene Funk",
        "Lorene Kris-Hilll",
        "Kevin Lubowitz",
        "Edmond Hahn",
        "Jeffrey Lowe",
        "Georgia Erdman",
        "Fannie Aufderhar",
        "Dr. Adam Leffler-Vandervort",
        "Faye Powlowski PhD",
        "Mr. Ralph Marvin",
        "Lewis Hermiston",
        "Darrin Turner",
        "Linda Hartmann",
        "Jasmine Turner V",
        "Cornelius Stanton",
        "Richard Bins I",
        "Darla Stanton",
        "Winifred Kuhn-Hudson",
        "Laverne O'Conner",
        "Rosa Bernier-Carter",
        "Doyle Steuber",
        "Tami Braun",
        "Lorene Mueller",
        "Dr. Alison Beatty",
        "Amelia Farrell",
        "Martin Pouros",
        "Ivan McCullough-Daniel",
        "Earnest Jacobi",
        "Van Runolfsdottir",
        "Mattie Glover",
        "Stephen Fay",
        "Lloyd Spinka",
        "Wilma Hoppe",
        "Kristopher Durgan",
        "Mr. Luis Sauer I",
        "Sonya Gorczany",
        "Dr. Raymond Maggio",
        "Larry Luettgen",
        "Carolyn Fritsch-Becker",
        "Julius Champlin",
        "Conrad Jacobs",
        "Ernesto Kshlerin",
        "Kristine Jacobs",
        "Jacqueline Goldner",
        "Joseph Krajcik-Effertz",
        "Mr. Guadalupe Bednar",
        "June Okuneva",
        "Leslie Fahey",
        "Willie Yundt",
        "Rosemary Renner",
        "Edmond Turcotte I",
        "Ira Kilback II",
        "Monica Schuster",
        "Merle Dibbert",
        "Elsie Padberg",
        "Terry Crooks",
        "Elbert Kuhic",
        "Terry Crona",
        "Walter Mertz",
        "Carmen Feil",
        "Miguel Wiegand",
        "Marta Sanford",
        "Henrietta Deckow",
        "Rosie Wunsch",
        "Kristen Cartwright",
        "Kristin Simonis",
        "Miss Margaret Towne MD",
        "Lindsay Mohr",
        "Ira Jerde",
        "Deborah Zulauf DDS",
        "Nina Runolfsson",
        "Terrell McDermott IV",
        "Dr. Stuart Farrell",
        "Daryl Leuschke",
        "Jeanne Wolff",
        "Kristin Renner",
        "Erica Batz",
        "Dr. Gilberto Hickle-Jenkins",
        "Angel Bergnaum",
        "Mae Schinner",
        "Jo Sanford V",
        "Pat Huels",
        "Delia Purdy",
        "Blanca Dach",
        "Kerry Wehner",
        "Krista Crist",
        "Lydia Runolfsdottir",
        "Pearl Swaniawski",
        "Shari McDermott",
        "Ryan Mayert",
        "Shirley Hegmann",
        "Kristen Stroman-Wisozk",
        "Gabriel Gottlieb-Turner",
        "Antonio Torphy",
        "Salvatore Swaniawski",
        "Danny Stark",
        "Jill Lueilwitz III",
        "Matthew Lueilwitz DDS",
        "Mrs. Elena Gutkowski",
        "Marcella Harber",
        "Kristi Barton",
        "Rick VonRueden",
        "Sabrina Ledner III",
        "Dwayne O'Connell",
        "Maggie Kuhic",
        "Dennis O'Kon",
        "Margaret Hartmann",
        "Nora Walker",
        "Marvin Pfeffer",
        "Gerald Roberts",
        "Dale Reichert",
        "Esther Huels",
        "Tina Erdman II",
        "Juana Pollich",
        "Derek Toy",
        "Sally Kuhn",
        "Martha Rempel",
        "May Trantow-Buckridge",
        "Faye Ratke V",
        "Daryl Rosenbaum",
        "Nina Hodkiewicz",
        "Dan Glover",
        "Mr. Sherman Ritchie",
        "Ernesto Wiza-Cummings",
        "Ms. Eva Bogisich III",
        "Gordon Murray",
        "Micheal Price",
        "Irma McGlynn",
        "Courtney Cormier Jr.",
        "Patsy Rosenbaum",
        "Glenda Davis",
        "Mr. Kirk Blanda",
        "Aubrey Feest",
        "Ms. Allison Labadie",
        "Dr. Felicia Rohan",
        "Russell Brown",
        "Malcolm Effertz",
        "Elaine Aufderhar Sr.",
        "Dr. Dominic Cassin",
        "Mrs. Alison Gorczany",
        "Dolores Gutmann",
        "Sara Mueller",
        "Dr. Darin Auer",
        "Douglas Parker",
        "Cora Adams",
        "George Murray",
        "Derek Williamson",
        "Lana Waelchi",
        "Jean Koch",
        "Francis Ebert",
        "Mrs. Janis Moen",
        "Jeanne Schamberger",
        "Kelly Graham",
        "Beulah Watsica-Fisher",
        "Lela Koch PhD",
        "Dwight Lubowitz",
        "Albert Koch",
        "Silvia Larkin",
        "Traci Hamill DVM",
        "Damon Boyer",
        "Dr. Muriel Gerhold",
        "Dora Hartmann",
        "Margaret Wolff",
        "Joshua Mitchell",
        "Frederick Marks",
        "Ms. Willie Morissette",
        "Lynne Muller",
        "Pearl Flatley DDS",
        "Angelina Lockman",
        "Cary Bernhard",
        "Marcos Feil",
        "Luke Erdman",
        "Mr. Toby Carter",
        "Ana Baumbach",
        "Donnie Heidenreich",
        "Gina Becker",
        "Homer Jerde",
        "Velma Schiller",
        "Woodrow Medhurst",
        "Maurice Ratke",
        "Meredith Langworth",
        "Bridget Lubowitz",
        "Lance Kovacek",
        "Tasha Dietrich",
        "Earnest Corwin",
        "Byron Klein",
        "Stephen Wilderman",
        "Alma Schiller",
        "Craig Turner",
        "Stacy Langworth II",
        "Debbie Kshlerin",
        "Christina Bartell",
        "April Marquardt",
        "Jesse Rutherford",
        "Zachary Torp",
        "Jermaine Moen",
        "Jerald Hackett-Little",
        "Jamie Bailey-Ferry",
        "Faye Reinger",
        "Bradley Pouros",
        "Wayne Bode",
        "Dr. Ken Wilkinson IV",
        "Leroy Nienow Jr.",
        "Dr. Joseph Bayer-Kshlerin",
        "Garrett Fisher",
        "Alexis Becker",
        "Eugene Deckow",
        "Daisy Kerluke",
        "Dianna Rippin",
        "Robin Zboncak",
        "Martha Fisher",
        "Lewis Wolf IV",
        "Suzanne O'Kon",
        "Juanita Davis",
        "Gerard Armstrong",
        "Dawn O'Kon Sr.",
        "Irvin Robel",
        "Mable Monahan",
        "Freddie D'Amore",
        "Dr. Erik Langosh",
        "Jodi Lowe",
        "Roosevelt McLaughlin",
        "Jane O'Keefe",
        "Randolph Hayes",
        "Dr. Leland Marquardt-Armstrong",
        "Derrick Bogan",
        "Marvin Adams",
        "Verna Labadie-Braun",
        "Lorena Hahn",
        "Bennie Lind",
        "Clifton Rohan",
        "Hugh Bernier",
        "Domingo Kris",
        "Tina Hodkiewicz",
        "Dr. Andre Jast",
        "Stephanie O'Keefe-Bartoletti",
        "Miss Jodi Gibson DDS",
        "Darin Turner",
        "Eugene Douglas III",
        "Roy Mueller",
        "Ms. Ora Doyle",
        "Gilberto Mills",
        "Darla Kautzer",
        "Mr. Erik Wiegand",
        "Rufus Pouros I",
        "Trevor West",
        "Lorena Jones",
        "Mrs. Eloise Keeling",
        "Drew Wyman I",
        "Willis Schaefer",
        "Brandon McGlynn",
        "Beth Beatty",
        "Kim Nitzsche",
        "Dr. Byron Hodkiewicz",
        "Dr. Christian Willms",
        "Patty Cruickshank",
        "Betty Bailey",
        "Emily Deckow-Champlin",
        "Cory Dickinson",
        "Hubert Corwin",
        "Benjamin West",
        "Margaret Prosacco",
        "Harvey Prosacco",
        "Tamara Hartmann",
        "Judith Hamill",
        "George McKenzie",
        "Guy Kautzer",
        "Alberta Becker",
        "Guillermo Morar",
        "Marsha Pfeffer",
        "Erin Crist",
        "Bridget Lakin",
        "Sheryl Quitzon",
        "Luther Wisozk",
        "Kari West II",
        "Misty Leffler",
        "Mae Rempel",
        "Janis Schultz",
        "Glen Blick",
        "Armando Lindgren",
        "Cary Rutherford",
        "Luz Bartoletti",
        "Betsy Kreiger",
        "Lee Turner",
        "Melba Yost",
        "Mrs. Josefina Bayer",
        "Merle Davis-Ondricka",
        "Courtney Rau",
        "Mr. Nicolas Gleichner",
        "Louis Raynor",
        "Dr. Robin Marvin",
        "Alfredo McLaughlin",
        "Ms. Katrina Carter",
        "Susie Windler",
        "Patty Armstrong-Ratke",
        "Jack Cruickshank",
        "Devin Walter",
        "Abraham Feest",
        "Sheila Schimmel",
        "Eleanor Hessel",
        "Dr. Tina Crist",
        "Dr. Marcos Schmidt",
        "Melvin Blanda",
        "Gordon Pfannerstill",
        "Anita Hane",
        "Joan Lindgren",
        "Ms. Leona Roberts",
        "Paula Ward",
        "Felix Cummerata",
        "Freddie Ebert",
        "Wendell Mosciski",
        "Mrs. Dora Welch",
        "Mona Lubowitz",
        "Owen Swaniawski",
        "Ollie Hirthe",
        "Miss Joyce Stamm",
        "Emmett Zemlak",
        "Cecelia Windler-Conroy",
        "Jeremiah Doyle",
        "Kenny O'Connell",
        "Mr. Alonzo Schimmel",
        "Jenny Nitzsche-Hermann",
        "Brendan Kuphal",
        "Benjamin Larson-Kris",
        "Violet Glover PhD",
        "Mr. Tyrone Gerhold",
        "Mr. Grant Kshlerin",
        "Susan Weissnat",
        "Marco Grady",
        "Randy Turner",
        "Lula Koelpin",
        "Eunice Hettinger",
        "Lorene Weimann",
        "Kirk O'Connell",
        "Tyrone Runte",
        "Hilda Langworth",
        "Jeremiah Wisoky Jr.",
        "Benny Parisian",
        "Ira Buckridge",
        "Belinda Crist",
        "Irene Armstrong",
        "Sadie Friesen",
        "Thomas Breitenberg",
        "Jerome Langosh V",
        "Perry Maggio",
        "Esther Gleason",
        "Jacqueline Gutmann",
        "Ms. Leah Grant DDS",
        "Tommy Veum",
        "Clayton Frami",
        "Jessie Kerluke",
        "Marjorie Quigley",
        "Veronica Ebert",
        "Hope Hand",
        "Stella Cummings",
        "Helen Fahey",
        "Kerry Becker DDS",
        "Allison Durgan",
        "Miss Janis Hessel",
        "Rosalie Hodkiewicz",
        "Eunice Robel V",
        "Pamela Rau-Ziemann",
        "Dallas Quitzon Jr.",
        "Tracy Windler",
        "Spencer Reilly",
        "Noah Mann",
        "Tricia Bernhard",
        "Rosie Rice",
        "Sean Kulas",
        "Neal Green",
        "Spencer Kihn",
        "Peggy Murray",
        "Cora Roob",
        "Catherine Green V",
        "Marcus Collins",
        "Nelson MacGyver",
        "Lola Moore",
        "Christian Champlin",
        "Della Homenick",
        "Miss Elisa Weimann",
        "Mr. Brad O'Conner",
        "Dale Nolan",
        "Billy Parker",
        "Nathan Littel",
        "Rodolfo Nikolaus",
        "Tanya Kunde",
        "Charlene Hessel-Hills",
        "Bob Fahey",
        "Miranda Kilback",
        "Benjamin Windler",
        "Tamara VonRueden",
        "Leo Willms III",
        "Arlene Jaskolski",
        "Otis Ryan",
        "Mr. Ismael Volkman",
        "Randall Bosco",
        "Brandon Cormier",
        "Ms. Carolyn Kilback",
        "Tabitha Zieme",
        "Nick Dooley",
        "Lena Steuber",
        "Miriam Waters Jr.",
        "Mrs. Essie Gleason",
        "Benny Kertzmann",
        "John Morar",
        "Ivan Volkman",
        "Ron Doyle PhD",
        "Dr. Tommie Gorczany",
        "Ervin Crooks",
        "Violet Armstrong",
        "Brett Beatty",
        "Angelica Collier",
        "Neal Feil",
        "Clarence Rau-Predovic",
        "Colin Daugherty",
        "Lloyd Lockman",
        "Mr. Dexter Mertz Sr.",
        "Kelvin Roberts",
        "Eileen Hyatt Sr.",
        "Mitchell Keeling",
        "Kenny Jacobi DDS",
        "Mr. Nelson Mann",
        "Robyn Funk",
        "Flora VonRueden-Wiza",
        "Cary Rice",
        "Misty Bednar",
        "Mae Metz",
        "Steven Padberg-Mayer",
        "Marilyn Hessel-Watsica DDS",
        "Miss Francis Hyatt",
        "Eduardo Dickens III",
        "Adrienne Larkin III",
        "Yvette Heathcote",
        "Paul Schaden",
        "Ismael Emard",
        "Mrs. Betsy Reinger",
        "Geoffrey Reinger",
        "Lee Weber II",
        "Rochelle Pfeffer",
        "Manuel Herzog",
        "Viola Gottlieb",
        "Shawn Hills DVM",
        "Christopher Zboncak",
        "Wilbur Miller",
        "Christie Wolff",
        "Sue Cole-Deckow",
        "Desiree Conroy",
        "Shawn Hirthe",
        "Bobbie Hermann",
        "Misty Heller I",
        "Elsie Cartwright",
        "Herman Langosh",
        "Ebony Mayert",
        "Alicia Wintheiser",
        "Raquel Daniel",
        "Margie Kiehn",
        "Mary Beer-Gerlach",
        "Pat Monahan",
        "Tommy Torp",
        "Ms. Kristy Moen",
        "Meredith Batz",
        "Opal Wisoky",
        "Carl Schimmel",
        "Katrina Labadie",
        "Dr. Verna Hilll",
        "Marsha Bruen",
        "Robin Gusikowski",
        "Lowell Bashirian",
        "Donnie Cassin",
        "Rudy Mills Sr.",
        "Toni Kirlin-Runte",
        "Darryl Smitham-Bergstrom",
        "Doug Langworth",
        "Dr. Rogelio Block",
        "Stewart Stoltenberg DVM",
        "Winifred Bogisich",
        "Rachael Toy",
        "Cheryl Stiedemann",
        "Marian Bruen",
        "Edna Herman",
        "Leo Ruecker",
        "Ms. Freda Padberg",
        "Wilbert Lubowitz",
        "Desiree Walker",
        "Heather Purdy",
        "Tasha Lynch DVM",
        "Maxine Maggio",
        "Sammy Rolfson",
        "Kristen Ondricka",
        "Kyle Jacobi",
        "Leah Ullrich",
        "Miss Susie Nikolaus",
        "Adrian O'Connell",
        "Rosie Crist",
        "Dr. Lila Herman",
        "Cristina Jones",
        "Mrs. Ella Hilpert",
        "Gerard Harber",
        "Anita Wolff",
        "Pete Gutmann",
        "Emilio Kemmer",
        "Kristy D'Amore-Hauck",
        "Marcella Roberts Jr.",
        "Edmond McKenzie III",
        "Timmy Kautzer-Hickle DDS",
        "Naomi Adams",
        "Cedric Wyman",
        "Eduardo Herman",
        "Dana Tillman IV",
        "Herbert Bins",
        "Kent Bogan",
        "Lionel McLaughlin-Bins",
        "Terrence Hauck",
        "Guillermo Mohr-Corkery",
        "Rachael Schoen",
        "Miss Marcia Padberg",
        "Dora Halvorson",
        "Rodolfo Jacobs",
        "Darrell Wiza",
        "Lorene Cartwright IV",
        "Susie Stokes MD",
        "Oliver Bergnaum",
        "Mildred Bernhard-Cassin",
        "Jason Rath",
        "Ms. Brandy Tremblay",
        "Courtney Stehr",
        "Guy Auer-Bechtelar",
        "Ramona Schmidt",
        "Ida Sawayn",
        "Tammy Bailey-Wiza",
        "Howard Stroman",
        "Sonya Christiansen",
        "Dexter Rodriguez",
        "Bernice Watsica",
        "Melvin Yundt",
        "Brenda Walker",
        "Rachel Johnston",
        "Marcus Gleason",
        "Roger Von",
        "Stephanie Crist",
        "Jerome Howell",
        "Gina Homenick",
        "Dr. Silvia Greenfelder",
        "Jerome Wintheiser-Franecki",
        "Josefina Weber",
        "Robert Lowe",
        "Reginald Hegmann",
        "Freda Goldner",
        "Dr. Eileen Bins",
        "Lula Cruickshank-Hessel",
        "Roberto Upton",
        "Miss Margie Rice",
        "Dr. Geoffrey Hirthe",
        "Lena Swift",
        "Denise Quitzon",
        "Gregg Wisozk",
        "Renee Goyette",
        "Marty Hamill",
        "Gayle Yundt",
        "Jamie Hirthe",
        "Alex Bernhard MD",
        "May McClure",
        "Franklin MacGyver",
        "Jan Mills",
        "Jasmine Block",
        "Cynthia Jacobson",
        "Drew Lynch",
        "Betty Tromp",
        "Wilbur Paucek",
        "Mark Murray",
        "Randal Ritchie",
        "Jason Bradtke",
        "Carolyn McClure",
        "Alton Hills",
        "Aubrey Rath",
        "Alfred Mann",
        "Lester Braun III",
        "Zachary Spencer III",
        "Joe Carroll",
        "Juanita Purdy IV",
        "Russell Daugherty",
        "Pedro Simonis DVM",
        "Gabriel Anderson",
        "Alton Bruen",
        "Zachary Stehr",
        "Verna Cummings",
        "Ms. Sophia Zemlak",
        "Luther Corkery",
        "Brian Wehner-Kuvalis",
        "Shelly Stanton",
        "Beatrice Rempel-Mosciski",
        "Lee Kreiger-Kunde",
        "Nichole Mosciski II",
        "Whitney Murazik",
        "Kristina Willms",
        "Darryl Armstrong",
        "Mr. Dwayne Runolfsdottir",
        "Walter Nikolaus",
        "Clinton Bergstrom",
        "Wilbur Howe",
        "Roland Terry I",
        "Virgil Predovic-Kertzmann",
        "Priscilla Schamberger",
        "Molly Sanford",
        "Mrs. Catherine Cronin",
        "Gina Rolfson",
        "Roosevelt Robel",
        "Lyle Connelly",
        "Brandi Ondricka",
        "Nelson Fisher-Bode PhD",
        "Mr. Noel Adams",
        "Arthur Cole",
        "Amber Vandervort",
        "Vincent Turcotte",
        "Dr. Lois Sipes",
        "Ernestine Lueilwitz",
        "Kellie Jacobi",
        "Emily Schaden",
        "Jennie Huels",
        "Dr. Jeffrey Langosh",
        "Mr. Bernard Gerlach",
        "Perry Lind",
        "Mona Dach",
        "Terry Ondricka",
        "Emilio Rice",
        "Jennie Rodriguez DVM",
        "Roosevelt Windler",
        "Henry Balistreri",
        "Josh Rosenbaum-Raynor",
        "Gerald Carroll DVM",
        "Ms. Tracey McGlynn",
        "Juana Howell",
        "Carole Harvey",
        "Lindsey Koch Jr.",
        "Stephen Stroman",
        "Dr. Alex D'Amore",
        "Ryan Maggio IV",
        "Laura Lesch I",
        "Nathan Kerluke"
]

await Promise.all(names.map(async (name) => {
    const [rows] = await connection.query(
        `select * from users where name = ?`,
        [name]
    )
    console.log(name)
}))
console.timeEnd("read")
